config/routes.rb
Rails.application.routes.draw do

  get 'pictures/get'
  post 'pictures/save'
  get 'pictures/show'
  get 'pictures/picture'

  resources :pictures
  get 'admin', to: 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users


  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root to: 'store#index'
  end
  get 'store/index'
  get 'contact', to: 'store#contact', as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.inject(0) { |sum, item| sum+item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart
  
  def total_price 
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, :email, :address, :pay_type, presence: true

  has_many :line_items, dependent: :destroy

  TYPES = ["Check", "Credit card", "Purchase order"].freeze

  enum pay_type: TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  
  def uploaded_picture=(picture_field)
    self.name = base_part_of(picture_field.original_filename) 
    self.content_type = picture_field.content_type.chomp
    self.data = picture_field.read
  end

  def base_part_of(file_name) 
    File.basename(file_name).gsub(/[^\w._-]/, '')
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, uniqueness: true
  validates :title, :description, :image_url, :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}

  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item  

  def book_name
    title
  end
  
  private
  def ensure_not_referenced_by_any_line_item 
    if line_items.empty?
      return true 
    else
      errors.add(:base, 'Line Items present')
      return false 
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains 

  
  class Error < StandardError
  end
  
  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last user"
    end 
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:destroy]
  def index
    @carts = Cart.all 
  end

  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_path, notice: "Invalid cart"  
    end 
  end

  def destroy
    @cart.destroy
    session[:cart_id] = nil
    redirect_to store_index_url
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  skip_before_action :authorize
  before_action :set_cart
  
  def index
    if params[:set_locale]
      redirect_to store_index_url(locale: params[:set_locale]) 
    else
      @products = Product.order(:title) 
    end
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users  = User.order(:name)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user
      redirect_to users_url, notice: "User #{@user.name} was successfully created."
    else
      render 'new', notice: @user.errors
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_url
    end
  end
  rescue_from 'User::Error' do |exception|
    redirect_to users_url, notice: exception.message
  end 

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"]= "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart.html.erb
<h2><%= t('.title') %></h2>
<table>
  <!-- render() renders all the line items by iterating the collection provided -->
  <%= render(cart.line_items) %>
  <tr class = "total_line">
    <td>Total</td>
    <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
  </tr>
</table>
  <%= button_to t('.checkout'), new_order_path, method: :get %>
<div class="empty_cart">
  <%= button_to t('.empty'), cart, method: :delete, data: {confirm: "Are you sure"}  %>
</div>

app/views/carts/show.html.erb
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
 <%= render @cart %>

app/views/users/_form.html.erb
<div class="depot_form">
  <%= form_for User.new do |f|%>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %>prohibited this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %> 
            <li><%= msg %></li>
          <% end %>
        </ul> 
      </div>
    <% end %>
    <fieldset>
      <legend>Enter User Details</legend>
      <div class="field">
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name, size: 40 %>
      </div>
      <div class="field">
        <%= f.label :password, "Password:" %>
        <%= f.password_field :password, size: 40 , id: 'password'%>
      </div>
      <div class="field">
        <%= f.label :password_confirmation, 'Confirm:' %>
        <%= f.password_field :password_confirmation, size: 40, id: 'password_confirmation' %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form'%>

app/views/users/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p> 
<% end %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
  <%= link_to "New User", new_user_path%>
</table>

app/views/users/new.html.erb
<%= render 'form' %>