config/routes.rb
Rails.application.routes.draw do

  get 'pictures/get'
  post 'pictures/save'
  get 'pictures/show'
  get 'pictures/picture'

  resources :pictures
  get 'admin', to: 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users


  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root to: 'store#index'
  end
  get 'store/index'
  get 'contact', to: 'store#contact', as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.inject(0) { |sum, item| sum+item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart
  
  def total_price 
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, :email, :address, :pay_type, presence: true

  has_many :line_items, dependent: :destroy

  TYPES = ["Check", "Credit card", "Purchase order"].freeze

  enum pay_type: TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  
  def uploaded_picture=(picture_field)
    self.name = base_part_of(picture_field.original_filename) 
    self.content_type = picture_field.content_type.chomp
    self.data = picture_field.read
  end

  def base_part_of(file_name) 
    File.basename(file_name).gsub(/[^\w._-]/, '')
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, uniqueness: true
  validates :title, :description, :image_url, :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}

  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item  

  def book_name
    title
  end
  
  private
  def ensure_not_referenced_by_any_line_item 
    if line_items.empty?
      return true 
    else
      errors.add(:base, 'Line Items present')
      return false 
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains 

  
  class Error < StandardError
  end
  
  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last user"
    end 
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:destroy]
  def index
    @carts = Cart.all 
  end

  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_path, notice: "Invalid cart"  
    end 
  end

  def destroy
    @cart.destroy
    session[:cart_id] = nil
    redirect_to store_index_url
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show,:edit, :update, :destroy]

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    respond_to do |f|
      if @product.save
        f.html { redirect_to @product }
        f.js 
      else
        f.html { render 'new' }
      end
    end
  end
  
  def index
    @products = Product.all
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Product Updated"
      @products = Product.all
      ActionCable.server.broadcast 'products', html: render_to_string('store/index',layout: false)
    else
      render 'edit'
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path, notice: "Product Deleted"
    end
  end

  private
  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price)
  end
  def find_product
    @product = Product.find(params[:id]) 
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  skip_before_action :authorize
  before_action :set_cart
  
  def index
    if params[:set_locale]
      redirect_to store_index_url(locale: params[:set_locale]) 
    else
      @products = Product.order(:title) 
    end
  end
  
  def contact
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"]= "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize @product.errors.count, "error"%> prohibited this product from bieng saved.</h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %> 
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>   
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>     
<% end %>  

app/views/products/_new.html.erb
<center>
  <div class="panel">
    <%= render 'form' %>
    <%= link_to 'cancel', '#' %>
  </div>
</center>

app/views/products/_products.html.erb
<% @products.each do |product| %>
  <tr class = "<%= cycle('list_line_odd', 'list_line_even')%> ">
  <td>
    <%= image_tag product.image_url, class: 'list_image', alt: 'image.txt' %>
  </td>
  <td class = 'list_description'>
    <dl>
      <dt>
        <%= product.title %>
      </dt>
      <dd>
        <%= product.description.truncate(50)%>
      </dd>
    </dl>
  </td>
  <td class = "list_actions">
    <%= link_to 'Show', product_path(product) %></br>
    <%= link_to 'Edit', edit_product_path(product) %></br>
    <%= link_to 'Delete', product_path(product), method: :delete %></br>
  </td>
</tr>
<% end %>

app/views/products/edit.html.erb
<center>  
  <h1> Edit Product </h1>
  <%= render 'form' %>
</center> 

app/views/products/index.html.erb
<center>
  <h1> Products List </h1> 
  <p  id='product_form' > Click <%= link_to 'here', new_product_path, remote: true %> to create new product.</p>
  <table>
    <%= render 'products'%>
  </table>  
</center>

app/views/products/new.html.erb
<center>
  <h1> New Product </h1>
  <%= render 'form' %>
</center>

app/views/products/new.js.erb
$("#product_form").replaceWith("<%= escape_javascript(render 'new') %>");

app/views/products/show.html.erb
<center>
<%= image_tag @product.image_url , class: 'product-image'%><br>
<b>Title:</b><%= @product.title %><br>
<b>Description:</b><%= @product.description %><br>
<b>Price: </b>$<%= @product.price %><br>
 
<%= link_to 'Back', products_path %> | <%= link_to 'Edit', edit_product_path(@product)%> | <%= link_to 'Delete', product_path(@product), method: :delete,data: {confirm: 'Are You Sure?'}  %>
</center>