config/routes.rb
Rails.application.routes.draw do

  get 'pictures/get'
  post 'pictures/save'
  get 'pictures/show'
  get 'pictures/picture'

  resources :pictures
  get 'admin', to: 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users


  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root to: 'store#index'
  end
  get 'store/index'
  get 'contact', to: 'store#contact', as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.inject(0) { |sum, item| sum+item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart
  
  def total_price 
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, :email, :address, :pay_type, presence: true

  has_many :line_items, dependent: :destroy

  TYPES = ["Check", "Credit card", "Purchase order"].freeze

  enum pay_type: TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  
  def uploaded_picture=(picture_field)
    self.name = base_part_of(picture_field.original_filename) 
    self.content_type = picture_field.content_type.chomp
    self.data = picture_field.read
  end

  def base_part_of(file_name) 
    File.basename(file_name).gsub(/[^\w._-]/, '')
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, uniqueness: true
  validates :title, :description, :image_url, :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}

  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item  

  def book_name
    title
  end
  
  private
  def ensure_not_referenced_by_any_line_item 
    if line_items.empty?
      return true 
    else
      errors.add(:base, 'Line Items present')
      return false 
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains 

  
  class Error < StandardError
  end
  
  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last user"
    end 
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"]= "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1> 
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/_side_bar.html.erb
<div id="side">
  <div id="cart"> 
    <% if @cart %>
      <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
        <%= render @cart %> 
      <% end %>
    <% end %>
  </div>
  <ul>
    <li><%= link_to t('.home'), '/' %></li>
    <li><%= link_to t('.questions'), "#" %></li>
    <li><%= link_to t('.news'), '#' %></li>
    <li><%= link_to t('.contact'), '/contact' %></li>
  </ul>
  <% if session[:user_id] %> 
    <ul>
      <li><%= link_to 'Orders', orders_path %></li> 
      <li><%= link_to 'Products', products_path %></li> 
      <li><%= link_to 'Users', users_path %></li>
    </ul>
    <%= button_to 'Logout', logout_path, method: :delete %> 
  <% else %>
    <%= button_to 'Login', login_path, method: :get %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.title_html') %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = '<%= controller.controller_name%>' >
    <div id="banner">
      <%= form_tag store_index_path, class: 'locale', method: :get, style:'float:right; margin: -0.25em 0.1em;' do %>
        <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
      <% end %>
      <%= image_tag ("lorem.png")%><%= @page_title || "Abby's Bookshelf"%>
    </div>
    <div class="row">   
      <div class="columns">
        <%= render 'layouts/side_bar'%>
      </div>
      <div class="columns">
        <div id="main">
          <%= yield %>
        </div>
      </div>  
    </div>
    <div class="row1">
      <div class="columns1">
        <h4>Params</h4> <%= debug(params) %> 
      </div>
    </div>
  </body>
</html>